apiVersion: v1
kind: Service
metadata:
  name: booksreview-service
  labels:
    app: booksreview
spec:
  type: LoadBalancer
  selector:
      app: booksreview
  ports:
    - port: 80
      targetPort: 8080
