apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    database: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      database: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      name: mysql-pod
      labels:
        database: mysql
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password
          volumeMounts:
            - name: mysql-db-creation
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-db-creation
          configMap:
            name: booksreview-db-creation-script
