apiVersion: v1
kind: Service
metadata:
  name: booksreview-service
  labels:
    app: booksreview
    db: postgresql
spec:
  type: LoadBalancer
  selector:
      app: booksreview
      db: postgresql
  ports:
    - port: 80
      targetPort: 8080
